---
car_model: "#eeeeec"
cloud: "#f3f3f3"
roadmap: "#888a85"
global_cloud: "#888a85"
car: "#98e1e0"
truck: "#98e1e0"
bus: "#89e9b2"
bicycle: "#e7d9a1"
tricycle: "#fcaf3e"
pedestrian: "#fe9999"
barrier: "#73d216"
construction_vehicle: "#fce94f"
motorcycle: "#3465a4"
traffic_cone: "#ad7fa8"
trailer: "#ad7fa8"
other: "#c4a000"
ignore: "#fce94f"
